---
- name: Set directory path
  set_fact:
    path: "{{wp_install_path}}/{{wp_directory_name}}"

- name: Only install Wordpress when there is no index.php in the path
  stat:
    path: "{{path}}/index.php"
  register: stat_result

- name: install wordpress
  block:
    - name: check installation path exists
      file: path={{path}} state=directory

    - name: download the latest wordpress version
      get_url: url=https://wordpress.org/latest.tar.gz force=no dest=/tmp/wordpress.tar.gz
    
    - name: unzip the folder
      unarchive: src=/tmp/wordpress.tar.gz dest=/tmp copy=no

    - name: copy wordpress to the installation directory
      shell: cp -r -n /tmp/wordpress/* "{{ path }}"

    - file: path=/tmp/wordpress.tar.gz state=absent
    - file: path={{ path }} owner=root group=root  state=directory recurse=yes setype=httpd_sys_content_t
    - file: path={{ path }}/wp-content/ owner=root group=root mode=777 state=directory recurse=yes
    
  when: stat_result.stat.exists == False

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no
  become_method: sudo

- name: Copy WordPress config file
  template: src=wp-config.php dest={{ path }}

- name: Configure the Virtual Host Config
  template: src=vhost.conf.j2 dest=/etc/httpd/conf.d/wordpress.conf mode=0644
  when: ansible_distribution == 'CentOS'

- name: Create the Virtual Host Config
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/wordpress.conf mode=0644
  when: ansible_distribution == 'Ubuntu'

- name: Create the Virtual Host Config
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/wordpress.conf mode=0644
  when: ansible_distribution == 'Ubuntu'

- name: enable the Virtual Host
  file:
    src: /etc/apache2/sites-available/wordpress.conf
    dest: /etc/apache2/sites-enabled/wordpress.conf
    state: link
  notify: reload apache